version: 2
jobs:
  build:
    working_directory: /helmdir/data

    docker:
      - image: ubuntu:16.04

    environment:
      PROJECT_NAME: "test-api"

    steps:
      - checkout

      - run: apt-get update && apt-get -y install curl
      - run: curl https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz | tar xzf -
      - run: ln -s ./linux-amd64/helm /usr/local/bin/helm

      - run: helm list

      - run:
          name: Output something
          command: |
            echo "Build was done"

      - store_artifacts:
          path: /helmdir/data/tests
          destination: data-tests