version: 2
jobs:
  build:
    working_directory: ~/helmtest2

    docker:
      - image: ubuntu:16.04

    environment:
      PROJECT_NAME: "test-api"

    steps:
      - checkout
      
      - run: echo $KUBECONFIG

      - run: chmod +x ./.scripts/k8s.sh
      - run: ./.scripts/k8s.sh

      - run: pwd
      - run: ls -la
      - run: ls -la .kube/

      - run: chmod +x ./.scripts/helm.sh
      - run: ./.scripts/helm.sh

      - run:
          name: Output something
          command: |
            echo "Build was done"

      - store_artifacts:
          path: ~/helmtest
          destination: data-tests