version: 2
jobs:
  build:
    working_directory: /helmdir/data

    docker:
      - image: ubuntu:16.04

    environment:
      PROJECT_NAME: "test-api"

    steps:
      - checkout
      
      - run: chmod +x ./.scripts/k8s.sh
      - run: ./.scripts/k8s.sh

      - run: helm list

      - run:
          name: Output something
          command: |
            echo "Build was done"

      - store_artifacts:
          path: /helmdir/data/tests
          destination: data-tests