version: 2
jobs:
  build:
    working_directory: /workdir

    docker:
      - image: ubuntu:16.04

    environment:
      PROJECT_NAME: "test-api"
      KUBECONFIG: /workdir/.kube/config

    steps:
      - checkout
      
      - run: echo 'export PATH=$CIRCLE_WORKING_DIRECTORY:$PATH' >> $BASH_ENV

      - run: echo $BASH_ENV

      - run: chmod +x ./.scripts/k8s.sh
      - run: ./.scripts/k8s.sh

      - run: chmod +x ./.scripts/helm.sh
      - run: ./.scripts/helm.sh

      - run: helm list

      - run:
          name: Output something
          command: |
            echo "Build was done"

      - store_artifacts:
          path: ~/helmtest
          destination: data-tests